os: windows

language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

script:
  - export NODEPATH=$(where.exe node.exe)
  - export PROJECTDIR=$(pwd)
  - export YARNCACHE=$(yarn cache dir)
  - export TEMPDIR=$LOCALAPPDATA\\Temp
  - powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
  - powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
  - powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
  - powershell Add-MpPreference -ExclusionPath ${TEMPDIR}
  - echo "DisableArchiveScanning..."
  - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"
  - echo "DisableBehaviorMonitoring..."
  - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"
  - echo "DisableRealtimeMonitoring..."
  - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
  - echo "Running yarn release..."
  - yarn release --win;