export const ADD_CHARACTER = 'ADD_CHARACTER';

export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';

export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';

export const UPDATE_CHARACTERS_LIST = 'UPDATE_CHARACTERS_LIST';

export const ADD_CHARACTER_TO_LIST = 'ADD_CHARACTER_TO_LIST';

export const REMOVE_CHARACTER_FROM_LIST = 'REMOVE_CHARACTER_FROM_LIST';

export const INSERT_CHARACTER_IN_LIST = 'INSERT_CHARACTER_IN_LIST';

export const UPDATE_FOCUSED_CHARACTER_INDEX = 'UPDATE_FOCUSED_CHARACTER_INDEX';
