export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const UPDATE_SETTINGS_STORAGE = 'UPDATE_SETTINGS_STORAGE';

export const UPDATE_SHARED_SETTINGS = 'UPDATE_SHARED_SETTINGS';

export const TOGGLE_SHORTCUTS = 'TOGGLE_SHORTCUTS';
